// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    cookieSecret: 'myBlog',
    db: 'nodejs-blog-refactor',
    url: 'mongodb://think2011:demo111111@kahana.mongohq.com:10098/nodejs-blog-refactor'
  };

}).call(this);

//# sourceMappingURL=settings.map
