// Generated by CoffeeScript 1.7.1
(function() {
  var Comment, mongodb;

  mongodb = require('./db');

  Comment = (function() {
    function Comment(comment) {
      this.name = comment.name, this.title = comment.title, this.time = comment.time, this.comment = comment.comment;
    }


    /* 保存 */

    Comment.prototype.save = function(callback) {
      var post;
      post = {
        name: this.name,
        title: this.title,
        time: this.time,
        comment: this.comment
      };
      return mongodb.open(function(err, db) {
        if (err) {
          return callback(err);
        }
        return db.collection('posts', function(err, collection) {
          if (err) {
            mongodb.close();
            return callback(err);
          }
          return collection.update({
            name: post.name,
            title: post.title,
            time: +post.time
          }, {
            $push: {
              'comments': post.comment
            }
          }, function(err) {
            mongodb.close();
            if (err) {
              return callback(err);
            }
            return callback(null);
          });
        });
      });
    };

    return Comment;

  })();

  module.exports = Comment;

}).call(this);

//# sourceMappingURL=comment.map
